finish - CardTray component and "edit-card" feature
brittneypostma/workflow pull request #27
Opened 2021-02-25 07:18 UTC by usamavarikkottil

## Changes
- [x] New `CardTray` component.
- [x] `CardTray` component opens upon clicking a card.
- [x] Ability to edit cards through the `CardTray` component.
- [x] Ability to delete cards through the `CardTray` component.

2021-02-25 11:50 UTC, lukaszwisniewski88 commented
just resolved local conflicts

2021-02-25 14:52 UTC, ChandlerBaskins requested changes

2021-02-25 14:52 UTC, ChandlerBaskins commented on src/actions/card.js
> +            column.cards = column.cards.filter(c => c.id != cardId);
prefer strict checks !==

2021-02-25 14:52 UTC, ChandlerBaskins commented on src/components/card.svelte
> +      card: card,
you can use  es6 short hand here for better  conciseness. IE {card}

2021-02-25 14:52 UTC, ChandlerBaskins commented on src/components/cardTray.svelte
> +      column: column,
we can use es6 shorthand here for more conciseness {column}

2021-02-25 14:52 UTC, ChandlerBaskins commented on src/components/cardTray.svelte
> +    <select id="status" bind:value={column} class="p-2 rounded">
Should remove commented out code

2021-02-25 14:52 UTC, ChandlerBaskins commented on src/components/column.svelte
> +          ><!-- deleteCard(columnID, cardID) -->
should remove commented out code

2021-03-01 19:48 UTC, brittneypostma approved these changes

2021-03-01 19:48 UTC, brittneypostma approved these changes

2021-03-01 19:48 UTC, merged